//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 12:07:55 PM WAT 
//


package com.ubn.devops.ubnncsintegration.ncsschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ubn.devops.ubnncsintegration.ncsschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeclarantCode_QNAME = new QName("", "DeclarantCode");
    private final static QName _SADAssessmentSerial_QNAME = new QName("", "SADAssessmentSerial");
    private final static QName _SADAssessmentNumber_QNAME = new QName("", "SADAssessmentNumber");
    private final static QName _CustomsCode_QNAME = new QName("", "CustomsCode");
    private final static QName _SADYear_QNAME = new QName("", "SADYear");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ubn.devops.ubnncsintegration.ncsschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SadAsmt }
     * 
     */
    public SadAsmt createSadAsmt() {
        return new SadAsmt();
    }

    /**
     * Create an instance of {@link EPaymentQuery }
     * 
     */
    public EPaymentQuery createEPaymentQuery() {
        return new EPaymentQuery();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeclarantCode")
    public JAXBElement<String> createDeclarantCode(String value) {
        return new JAXBElement<String>(_DeclarantCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SADAssessmentSerial")
    public JAXBElement<String> createSADAssessmentSerial(String value) {
        return new JAXBElement<String>(_SADAssessmentSerial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SADAssessmentNumber")
    public JAXBElement<String> createSADAssessmentNumber(String value) {
        return new JAXBElement<String>(_SADAssessmentNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomsCode")
    public JAXBElement<String> createCustomsCode(String value) {
        return new JAXBElement<String>(_CustomsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SADYear")
    public JAXBElement<Integer> createSADYear(Integer value) {
        return new JAXBElement<Integer>(_SADYear_QNAME, Integer.class, null, value);
    }

}
