//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 12:04:59 PM WAT 
//

package com.ubn.devops.ubnncsintegration.ncsschema;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import lombok.Data;

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@JacksonXmlRootElement(localName = "Payment")
public class Payment {

	@JsonProperty("MeansOfPayment")
	protected String meansOfPayment;
	@JsonProperty("Reference")
	protected String reference;
	@JsonProperty("Amount")
	protected double amount;

}
