//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 12:06:57 PM WAT 
//


package com.ubn.devops.ubnncsintegration.ncsschema;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlTransient;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.ubn.devops.ubnncsintegration.model.PaymentDetails;
import com.ubn.devops.ubnncsintegration.model.TaxEntity;

@JsonIgnoreProperties(ignoreUnknown = true)
@JacksonXmlRootElement(localName = "eAssessmentNotice")
public class EAssessmentNotice {

	@XmlTransient
	@JsonIgnore
	private PaymentDetails entity; 
	
	@XmlTransient
	@JsonIgnore
	private String assessmentFilename;
	
	@JacksonXmlProperty(isAttribute=true)
	private int version;
	
	public EAssessmentNotice() {
		
	}
	
	public EAssessmentNotice(PaymentDetails entity) {
		double totalAmount = 0;
		this.bankBranchCode = entity.getBankBranchCode();
		this.bankCode = entity.getBankCode();
		this.companyCode=entity.getCompanyCode();
		this.companyName=entity.getCompanyName();
		this.customsCode=entity.getCustomsCode();
		this.declarantCode=entity.getDeclarantCode();
		this.declarantName=entity.getDeclarantName();
		this.formMNumber=entity.getFormMNumber();
		this.SadAssessmentDate=entity.getSadAssessmentDate();
		this.SadAssessmentNumber=entity.getSadAssessmentNumber();
		this.SadAssessmentSerial=entity.getSadAssessmentSerial();
		this.SadYear=entity.getSadYear();
		List<Tax> taxesToBind = new ArrayList<>();
		for(TaxEntity taxEntity:entity.getTaxes()) {
			totalAmount +=taxEntity.getTaxAmount().doubleValue();
			Tax tax = new Tax();
			tax.setTaxAmount(taxEntity.getTaxAmount());
			tax.setTaxCode(taxEntity.getTaxCode());
			taxesToBind.add(tax);
		}
		this.taxes = new Taxes(taxesToBind);
		this.totalAmountToBePaid=new BigDecimal(totalAmount);
	}
	
    @JsonProperty("SADYear")
    private int SadYear;
    @JsonProperty("CustomsCode")
    protected String customsCode;
    @JsonProperty("DeclarantCode")
    protected String declarantCode;
    @JsonProperty("DeclarantName")
    protected String declarantName;
    @JsonProperty("SADAssessmentSerial")
    protected String SadAssessmentSerial;
    @JsonProperty("SADAssessmentNumber")
    protected String SadAssessmentNumber;
    @JsonProperty("SADAssessmentDate")
    protected String SadAssessmentDate;
    @JsonProperty("CompanyCode")
    protected String companyCode;
    @JsonProperty("CompanyName")
    protected String companyName;
    @JsonProperty("BankCode")
    protected String bankCode;
    @JsonProperty("BankBranchCode")
    protected String bankBranchCode;
    @JsonProperty("FormMNumber")
    protected String formMNumber;
    @JsonProperty("Taxes")
    protected Taxes taxes;
    @JsonProperty("TotalAmountToBePaid")
    protected BigDecimal totalAmountToBePaid;

	/**
	 * @return the entity
	 */
	public PaymentDetails getEntity() {
		return entity;
	}
	/**
	 * @param entity the entity to set
	 */
	public void setEntity(PaymentDetails entity) {
		this.entity = entity;
	}
	/**
	 * @return the sadYear
	 */
	public int getSadYear() {
		return SadYear;
	}
	/**
	 * @param sadYear the sadYear to set
	 */
	public void setSadYear(int sadYear) {
		SadYear = sadYear;
	}
	/**
	 * @return the customsCode
	 */
	public String getCustomsCode() {
		return customsCode;
	}
	/**
	 * @param customsCode the customsCode to set
	 */
	public void setCustomsCode(String customsCode) {
		this.customsCode = customsCode;
	}
	/**
	 * @return the declarantCode
	 */
	public String getDeclarantCode() {
		return declarantCode;
	}
	/**
	 * @param declarantCode the declarantCode to set
	 */
	public void setDeclarantCode(String declarantCode) {
		this.declarantCode = declarantCode;
	}
	/**
	 * @return the declarantName
	 */
	public String getDeclarantName() {
		return declarantName;
	}
	/**
	 * @param declarantName the declarantName to set
	 */
	public void setDeclarantName(String declarantName) {
		this.declarantName = declarantName;
	}
	/**
	 * @return the sadAssessmentSerial
	 */
	public String getSadAssessmentSerial() {
		return SadAssessmentSerial;
	}
	/**
	 * @param sadAssessmentSerial the sadAssessmentSerial to set
	 */
	public void setSadAssessmentSerial(String sadAssessmentSerial) {
		SadAssessmentSerial = sadAssessmentSerial;
	}
	/**
	 * @return the sadAssessmentNumber
	 */
	public String getSadAssessmentNumber() {
		return SadAssessmentNumber;
	}
	/**
	 * @param sadAssessmentNumber the sadAssessmentNumber to set
	 */
	public void setSadAssessmentNumber(String sadAssessmentNumber) {
		SadAssessmentNumber = sadAssessmentNumber;
	}
	/**
	 * @return the sadAssessmentDate
	 */
	public String getSadAssessmentDate() {
		return SadAssessmentDate;
	}
	/**
	 * @param sadAssessmentDate the sadAssessmentDate to set
	 */
	public void setSadAssessmentDate(String sadAssessmentDate) {
		SadAssessmentDate = sadAssessmentDate;
	}
	/**
	 * @return the companyCode
	 */
	public String getCompanyCode() {
		return companyCode;
	}
	/**
	 * @param companyCode the companyCode to set
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}
	/**
	 * @return the companyName
	 */
	public String getCompanyName() {
		return companyName;
	}
	/**
	 * @param companyName the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	/**
	 * @return the bankCode
	 */
	public String getBankCode() {
		return bankCode;
	}
	/**
	 * @param bankCode the bankCode to set
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}
	/**
	 * @return the bankBranchCode
	 */
	public String getBankBranchCode() {
		return bankBranchCode;
	}
	/**
	 * @param bankBranchCode the bankBranchCode to set
	 */
	public void setBankBranchCode(String bankBranchCode) {
		this.bankBranchCode = bankBranchCode;
	}
	/**
	 * @return the formMNumber
	 */
	public String getFormMNumber() {
		return formMNumber;
	}
	/**
	 * @param formMNumber the formMNumber to set
	 */
	public void setFormMNumber(String formMNumber) {
		this.formMNumber = formMNumber;
	}
	/**
	 * @return the taxes
	 */
	public Taxes getTaxes() {
		return taxes;
	}
	/**
	 * @param taxes the taxes to set
	 */
	public void setTaxes(Taxes taxes) {
		this.taxes = taxes;
	}
	/**
	 * @return the totalAmountToBePaid
	 */
	public BigDecimal getTotalAmountToBePaid() {
		return totalAmountToBePaid;
	}
	/**
	 * @param totalAmountToBePaid the totalAmountToBePaid to set
	 */
	public void setTotalAmountToBePaid(BigDecimal totalAmountToBePaid) {
		this.totalAmountToBePaid = totalAmountToBePaid;
	}
	
	/**
	 * @return the version
	 */
	public int getVersion() {
		return version;
	}

	/**
	 * @param version the version to set
	 */
	public void setVersion(int version) {
		this.version = version;
	}
	
	
	/**
	 * @return the assessmentFilename
	 */
	public String getAssessmentFilename() {
		return assessmentFilename;
	}

	/**
	 * @param assessmentFilename the assessmentFilename to set
	 */
	public void setAssessmentFilename(String assessmentFilename) {
		this.assessmentFilename = assessmentFilename;
	}

	@Override
	public String toString() {
		return "EAssessmentNotice [entity=" + entity + ", SadYear=" + SadYear + ", customsCode=" + customsCode
				+ ", declarantCode=" + declarantCode + ", declarantName=" + declarantName + ", SadAssessmentSerial="
				+ SadAssessmentSerial + ", SadAssessmentNumber=" + SadAssessmentNumber + ", SadAssessmentDate="
				+ SadAssessmentDate + ", companyCode=" + companyCode + ", companyName=" + companyName + ", bankCode="
				+ bankCode + ", bankBranchCode=" + bankBranchCode + ", formMNumber=" + formMNumber + ", taxes=" + taxes
				+ ", totalAmountToBePaid=" + totalAmountToBePaid + "]";
	}
    
    
   }
